### ISSUE TITLE
Specifying default value via the config file

### ISSUE THREAD

**Issue by hcivelek** [jessarcher/laravel-castable-data-transfer-object#17]
Hi, I want to thank you first for this package. is it possible to specify some default values in the cast **via the config file?** 

When I tried like:

```
namespace App\Values;

use JessArcher\CastableDataTransferObject\CastableDataTransferObject;

class LibraryConf extends CastableDataTransferObject
{
    public int $minDeliveryDays = config('preferences.min_delivery_days');
    public int $maxDeliveryDays = config('preferences.max_delivery_days');
    public int $maxLoanLimit = config('preferences.max_loan_limit');
}
```
I got: 

`Constant expression contains invalid operations`

I understand that is not a Laravel or this package's problem, it is PHP's problem, but is there any way to get around it? Or writing some defaults on the class directly is not a big deal?

**Comment by jessarcher** [comment]
I'd just put the defaults on the DTO class.

Alternatively, you could probably add a constructor something like this (untested):

```php
class LibraryConf extends CastableDataTransferObject
{
    // ...

    public function __construct(array $arguments)
    {
        $arguments['minDeliveryDays'] ??= config('preferences.min_delivery_days');

        parent::__construct($arguments);
    }
}
```

Hope that helps!
